package exceptions;

import java.sql.SQLException;

public class Exception1 {

	// public static void main(String[] args) throws Exception {
	// try {
	// throw new SQLException();
	// } catch (Throwable e) {
	// e.printStackTrace();
	// } finally {
	// throw new Exception();
	// }
	// }

	// public static void main(String[] args) {
	// try {
	// throw 10;
	// } catch (int e) {
	// System.out.println("Got the Exception");
	// }
	// }

	// public static void main(String[] args) {
	// try {
	// System.out.println("Hello world");
	// } finally {
	// System.out.println("Finally executing ");
	// }
	// }

	
	
	// public static void main(String[] args) {
	// try {
	// return;
	// } finally {
	// System.out.println("Finally");
	// }
	// }
	
	
	
	// public static void main(String[] args) {
	// try {
	// int a[] = {1,2,3,4};
	// for(int i = 1; i <= 4; i++) {
	// System.out.println(a[i]);
	// }
	// } catch(ArrayIndexOutOfBoundsException e) {
	// System.out.println("catch1");
	// }
	//
	// catch(Exception e) {
	// System.out.println("catch2");
	// }
	// }

}
